# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'iPoulet' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iPoulet
pod 'NVActivityIndicatorView'
pod 'FloatingActionSheetController'
pod 'PopupController'
pod 'LiquidFloatingActionButton'
pod 'Hokusai'
pod 'NumberMorphView'
pod 'Charts'
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'PopupDialog'
pod 'PasswordTextField'
pod 'PageMenu'

end
